name: flutter_notebook_chapter_47
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  hugeicons: ^1.1.1
  gap: ^3.0.1
  percent_indicator: ^4.2.5

  freezed_annotation: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: 
  build_runner: ^2.9.0

flutter:
  uses-material-design: true
